#ifndef SERVICES_H
#define SERVICES_H

enum e_ACTION_MESSAGEREQUEST_TYPE
{
    TESTPRIME = 0,
    NEXTPRIME,
    NEXTNPRIMES,
    GETDATE,
    FILETESTOPERATION
};

enum e_ACTION_MESSAGERESPONSE_TYPE
{
    RESPONSE_ERROR = 0,
    RESPONSE_TESTPRIME,
    RESPONSE_NEXTPRIME,
    RESPONSE_NEXTNPRIMES,
    RESPONSE_GETDATE,
    RESPONSE_FILETESTOPERATION
};

#endif
